import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
const p = await ctx.newPage()
const errs = []; p.on('pageerror', e => errs.push(e.message))
await p.goto('http://localhost:5174/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1500)
// click the About nav link (client-side nav → triggers transition + object morph)
await p.getByRole('link', { name: 'About', exact: true }).first().click()
await p.waitForTimeout(4000)
const url = p.url()
const hasSlot = await p.locator('.pg-hero-object').count()
const ccVisible = await p.evaluate(() => { const c = document.getElementById('canvas-container'); return !!c && !c.classList.contains('world-hidden') })
console.log('landed', url, 'slot', hasSlot, 'canvasVisible', ccVisible, 'errs', errs.length)
await ctx.close(); await b.close()
